# Generated by Django 5.0.3 on 2024-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesTrains',
            fields=[
                ('trainId', models.AutoField(primary_key=True, serialize=False)),
                ('terminus', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=10)),
            ],
        ),
    ]
